### ISSUE TITLE
about the style_loss backward

### ISSUE THREAD

**Issue by Stick-To** [jessemelpolio/non-stationary_texture_syn#15]
Is there any difference between (style_loss+perceptual_loss+gan_G).backward() and style_loss.backward(retain_graph=True) + (perceptual_loss+gan_G).backward()  ?
thanks

**Comment by jessemelpolio** [comment]
I haven't tried this implementation choice. Intuitively, I think this will have minor difference to the outcome. But maybe our implementation save more GPU consumption because the computational graph is maintained in the memory till calling the backward function again?
