### ISSUE TITLE
Generalization ability of model

### ISSUE THREAD

**Issue by Zheng222** [jessemelpolio/non-stationary_texture_syn#7]
@jessemelpolio Hello, I found that `scripts/train_half_style.sh` only takes one image (i.e. `datasets/half/202/train/202.jpg`) as your training data. In the testing phase, this trained model can only take the same image (i.e. `dataset/half/202/test/202.jpg`) as input and output a bigger one. What I want to know is whether this already trained model is only valid for this picture. If I want to test other image, does the model need to be retrained？I think this is a bit like [ZSSR](https://github.com/assafshocher/ZSSR).

**Comment by jessemelpolio** [comment]
@Zheng222 Sorry for the late reply. It's quite different from super resolution as we discussed in our paper. In fact, if you feed a well-trained model with other images, you can get an image with 2x size of the input. But the result is only structurally similar to the input but is similar to the training image in texture styles. This is also mentioned in our paper. See texture transfer parts and some amazing results.

**Comment by Zheng222** [comment]
@jessemelpolio Is it necessary to train a proprietary model parameter for each picture in your experiment?

**Comment by jessemelpolio** [comment]
Yes. It's normal in texture synthesis task.

**Comment by Zheng222** [comment]
Ok, thank you for your reply.
