### ISSUE TITLE
About experiments in your paper

### ISSUE THREAD

**Issue by wzm2256** [jessemelpolio/non-stationary_texture_syn#8]
Hi, I have a question that is not directly related to your algorithm. It's about the experiments in your paper.

I notice you compared your result with Self-tuning and MGANs in figure 7.  As far as I know,  the code for MGANs can not be used for texture synthesis, although they have these results in their paper, and there are some bugs in the code of self-tuning methods. How do you run their codes?

**Comment by jessemelpolio** [comment]
I just download their codes on github and make several minor changes without changing the network architecture and main ideas. Seeing that our results show similar characteristics with the results posted in their paper, we think those results are correct to some extent. Once in a while, we have the similar doubts with you (also the reviewers have pointed out this problem) and we carefully checked the code and just in case, we turned to another student to perform the same experiments based on their code. But similar results are achieved. Sorry that I forgot all the details for such a long time.

**Comment by wzm2256** [comment]
Thank all the same.
