### ISSUE TITLE
Augmentation of diversity by shuffling tiles

### ISSUE THREAD

**Issue by pdeperth** [jessemelpolio/non-stationary_texture_syn#9]
Hi, 

In your paper you mention diversity augmentation by giving shuffled tiles of the original image to the generator ; have you implemented this anywhere in github? 
Thank you.

**Comment by jessemelpolio** [comment]
Yes. You could refer to `util/random_tile.py` to produce enough images composed by random tiles and then feed them to the well-trained models to yield diverse results.

**Comment by pdeperth** [comment]
All right, thank you.
